test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

dymond_minio:
  service: S3
  endpoint: http://<vm-ip>:9000
  access_key_id: <%= ENV["MINIO_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["MINIO_SECRET_KEY"] %>
  region: us-east-1
  bucket: platform-assets
  force_path_style: true